### ISSUE TITLE
More onUse?

### ISSUE THREAD

**Issue by VineDark** [SmokeyStack/adk-lib#2]
How about new tags that executing command (or just function so it will be neat)? Like adk-lib:on_use_yourFunction (.MC function file, not the JS function), and perhaps that opening a form? Like adk-lib:on_use_yourForm. That's about it, sorry if you think this is too much 😓

**Comment by SmokeyStack** [comment]
Planning to add this functionality in the next release as experimental.

**Comment by SmokeyStack** [comment]
Implemented in the latest release: https://github.com/SmokeyStack/adk-lib/releases/tag/0.2.0-experimental.1.21.30.21
